name: Publish Package to npm
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: NPM
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install && yarn build
      - run: cd dist && yarn publish dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
